abstract class ApiKeys {
  static String token =
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3ZjYXJlLmludGVncmF0aW9uMjUuY29tL2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNzEyOTY3OTQ5LCJleHAiOjE3MTI5NzE1NDksIm5iZiI6MTcxMjk2Nzk0OSwianRpIjoiMFRjVUNxYmxSWVA2ZlhyQiIsInN1YiI6IjkwMCIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.YrRPLsoOmLcTZwBxQOkcIHXMkUR_fFxxEEdFalj2_Kk';
}
