abstract class ApiKeys {
  static String token =
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3ZjYXJlLmludGVncmF0aW9uMjUuY29tL2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNzEzMDEwNjc0LCJleHAiOjE3MTMwMTQyNzQsIm5iZiI6MTcxMzAxMDY3NCwianRpIjoieEdIZVYyMmQ5TTEwZTZDTiIsInN1YiI6IjkwMCIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.QTi12JLv4nT1eI2DhwhI4jFHsI6A4jjL5WijjogmGvk';
}
